import {CONFIG} from './config.js';
import {LocalStorageAdapter} from './storage/local-storage.js';
import {RemoteStorageAdapter} from './storage/remote-storage.js';
import {createSession,recordAttempt,scorePhase,exportSession} from './learning/session.js';
import {phaseSkillSequence,adaptDifficulty} from './learning/adaptive-engine.js';
import {generateTask} from './generators/registry.js';
import {validateAnswer} from './core/answer-validator.js';
import {inputTemplate,wireInput,collectAnswer} from './ui/inputs.js';
import {renderAllMath} from './ui/math-renderer.js';
import {NumberLine} from './ui/number-line.js';

const root=document.querySelector('#app');
const local=new LocalStorageAdapter(CONFIG.storageKey);const remote=new RemoteStorageAdapter(CONFIG.remoteStorageUrl);
let session=await local.load();let sequence=[],currentTask=null,hintLevel=0,numberLine=null,orderItems=[];
const phaseMeta={diagnostic:{title:'Phase 1 – Bruch-Check',length:CONFIG.diagnosticLength,next:'training'},training:{title:'Phase 2 – Individuelles Training',length:CONFIG.trainingLength,next:'mix'},mix:{title:'Phase 3 – Bruch-Mix',length:CONFIG.mixLength,next:'final'},final:{title:'Phase 4 – Abschlusscheck',length:CONFIG.finalLength,next:'results'}};

function page(html){root.innerHTML=html;renderAllMath(root)}
function showStart(){const saved=session&&!session.completed&&session.profile?.name;page(`<section class="card"><p class="muted">Mathematik · 3. Klasse Mittelschule</p><h1>Bruch-Check</h1><p>Wiederhole Bruchrechnen mit einem kurzen Check, persönlichem Training und einem Abschlusscheck. Es gibt keine Schulnote.</p>${saved?`<div class="feedback">Ein gespeicherter Stand von <strong>${session.profile.name}</strong> wurde gefunden.</div><div class="actions"><button id="resume">Fortsetzen</button><button id="restart" class="secondary">Neu starten</button></div>`:`<div class="grid two"><label class="field">Name oder Kürzel<input id="name" autocomplete="off"></label><label class="field">Klasse<input id="class" value="3b" autocomplete="off"></label></div><div class="actions"><button id="start">Bruch-Check starten</button></div>`}</section>`);
 if(saved){root.querySelector('#resume').onclick=()=>startPhase(session.phase,session.taskIndex||0);root.querySelector('#restart').onclick=async()=>{await local.clear();session=null;showStart()}}else root.querySelector('#start').onclick=async()=>{const name=root.querySelector('#name').value.trim();if(!name){root.querySelector('#name').focus();return}session=createSession({name,className:root.querySelector('#class').value.trim()});await local.save(session);startPhase('diagnostic',0)};
}
function startPhase(phase,index=0){session.phase=phase;session.taskIndex=index;sequence=phaseSkillSequence(phase,session.skills,phaseMeta[phase].length);showTask()}
function taskProgress(){return Math.round(session.taskIndex/sequence.length*100)}
function showTask(){const meta=phaseMeta[session.phase];if(session.taskIndex>=sequence.length){finishPhase();return}hintLevel=0;const skill=sequence[session.taskIndex];currentTask=generateTask(skill,adaptDifficulty(session.skills[skill]||{difficulty:1,errors:0,correctNoHelp:0}));const count=session.taskIndex+1;
 page(`<section class="card"><div class="grid"><div><strong>${meta.title}</strong><span class="muted"> · Aufgabe ${count} von ${sequence.length}</span></div><div class="progress" aria-label="Fortschritt"><span style="width:${taskProgress()}%"></span></div></div><div class="question"><p>${currentTask.promptText||''}</p>${currentTask.promptTex?`<div class="math" data-tex="${currentTask.promptTex}"></div>`:''}</div><div id="interaction"></div><div id="feedback"></div><div id="hint"></div><div class="actions"><button id="check">Prüfen</button><button id="hintBtn" class="secondary">Hinweis</button></div></section>`);
 const interaction=root.querySelector('#interaction');if(currentTask.type==='numberLine'){interaction.innerHTML='<div id="numberline"></div>';numberLine=new NumberLine(interaction.querySelector('#numberline'),currentTask.numberLine)}else if(currentTask.type==='order'){orderItems=currentTask.items.map(x=>x);renderOrder(interaction)}else{interaction.innerHTML=inputTemplate(currentTask);wireInput(interaction,currentTask)}
 root.querySelector('#check').onclick=checkCurrent;root.querySelector('#hintBtn').onclick=showHint;renderAllMath(root);
}
function renderOrder(container){container.innerHTML=`<div class="order-list">${orderItems.map((f,i)=>`<div class="order-item"><span data-tex="\\frac{${f.numerator}}{${f.denominator}}"></span><button class="secondary move" data-i="${i}" data-dir="-1" aria-label="Nach links">←</button><button class="secondary move" data-i="${i}" data-dir="1" aria-label="Nach rechts">→</button></div>`).join('')}</div>`;container.querySelectorAll('.move').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.i),j=i+Number(b.dataset.dir);if(j<0||j>=orderItems.length)return;[orderItems[i],orderItems[j]]=[orderItems[j],orderItems[i]];renderOrder(container);renderAllMath(container)});renderAllMath(container)}
function showHint(){const hints=currentTask.hints||[];const solutions=currentTask.solutionSteps||[];hintLevel=Math.min(4,hintLevel+1);session.hintsUsed++;let text='';if(hintLevel<=2)text=hints[Math.min(hintLevel-1,hints.length-1)]||'Überlege, welche bekannte Bruchregel hier passt.';else if(hintLevel===3)text=solutions[0]||hints.at(-1)||'Zerlege die Aufgabe in kleine Rechenschritte.';else text=solutions.join(' → ')||`Die Lösung lautet ${formatAnswer(currentTask.correctAnswer)}.`;root.querySelector('#hint').innerHTML=`<div class="hint"><strong>Hilfe ${hintLevel}</strong><div ${text.includes('\\')?'data-tex':''}>${text}</div></div>`;renderAllMath(root);local.save(session)}
function formatAnswer(a){if(a?.numerator!==undefined)return `${a.numerator}/${a.denominator}`;return String(a)}
function checkCurrent(){const btn=root.querySelector('#check');btn.disabled=true;let result,raw;
 if(currentTask.type==='numberLine'){raw={value:numberLine.getAnswer()};result=numberLine.isCorrect()?{status:'correct',correct:true,message:'Richtig platziert.'}:{status:'wrong',correct:false,message:'Noch nicht an der richtigen Stelle. Achte auf die Unterteilungen.'};}
 else if(currentTask.type==='order'){raw=orderItems.map(x=>x.toJSON());const correct=orderItems.every((x,i)=>x.equals(currentTask.correctAnswer[i]));result=correct?{status:'correct',correct:true,message:'Richtig geordnet.'}:{status:'wrong',correct:false,message:'Die Reihenfolge stimmt noch nicht. Vergleiche benachbarte Brüche.'};}
 else{raw=collectAnswer(root.querySelector('#interaction'),currentTask);result=validateAnswer(currentTask,raw)}
 const fb=root.querySelector('#feedback');const cls=result.status==='correct'?'ok':result.status==='almost'?'warn':'error';fb.innerHTML=`<div class="feedback ${cls}">${result.message}</div>`;
 if(result.status==='invalid'||result.status==='almost'){btn.disabled=false;return}recordAttempt(session,currentTask,result,hintLevel,raw);local.save(session);if(result.correct){fb.innerHTML+=`<div class="actions"><button id="next">Weiter</button></div>`;root.querySelector('#next').onclick=()=>{session.taskIndex++;local.save(session);showTask()}}else{btn.disabled=false}
}
async function finishPhase(){if(session.phase==='diagnostic')session.diagnosticScore=scorePhase(session,'diagnostic');if(session.phase==='final')session.finalScore=scorePhase(session,'final');const next=phaseMeta[session.phase].next;if(next==='results'){session.completed=true;await local.save(session);await remote.save(exportSession(session)).catch(()=>null);showResults();return}session.phase=next;session.taskIndex=0;await local.save(session);page(`<section class="card"><h2>${phaseMeta[next].title}</h2><p>${next==='training'?'Jetzt werden unsichere Bereiche häufiger geübt und sichere nur gelegentlich wiederholt.':next==='mix'?'Jetzt werden verschiedene Strategien bewusst gemischt.':'Zum Schluss folgt ein kurzer unabhängiger Check.'}</p><div class="actions"><button id="go">Weiter</button></div></section>`);root.querySelector('#go').onclick=()=>startPhase(next,0)}
function showResults(){const rows=Object.values(session.skills).filter(s=>s.attempts>0).sort((a,b)=>a.label.localeCompare(b.label));const improvement=(session.finalScore??0)-(session.diagnosticScore??0);page(`<section class="card"><h1>Deine Kompetenzübersicht</h1><div class="grid two"><div class="feedback"><strong>Diagnose</strong><br>${session.diagnosticScore??0}%</div><div class="feedback ok"><strong>Abschluss</strong><br>${session.finalScore??0}%</div></div><p><strong>Veränderung:</strong> ${improvement>=0?'+':''}${improvement} Prozentpunkte · <strong>${session.independentCorrect}</strong> Aufgaben selbstständig gelöst · <strong>${session.hintsUsed}</strong> Hilfen verwendet.</p><div class="skill-list">${rows.map(s=>`<div class="skill-row"><span>${s.label}</span><span class="tag">${s.confidence}</span></div>`).join('')}</div><div class="actions"><button id="export">Ergebnisdaten herunterladen</button><button id="new" class="secondary">Neue Runde</button></div></section>`);root.querySelector('#export').onclick=()=>{const blob=new Blob([JSON.stringify(exportSession(session),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bruch-check-${session.profile.name||'session'}.json`;a.click();URL.revokeObjectURL(a.href)};root.querySelector('#new').onclick=async()=>{await local.clear();session=null;showStart()}}
showStart();
