import {renderAllMath} from './math-renderer.js';
export function inputTemplate(task){
  if(task.answerType==='fraction')return `<div class="fraction-input"><label>Zähler<input id="num" inputmode="numeric" aria-label="Zähler"></label><label>Nenner<input id="den" inputmode="numeric" aria-label="Nenner"></label></div><div class="math" id="live-preview" aria-label="Vorschau"></div>`;
  if(task.answerType==='mixed')return `<div class="mixed-input"><label>Ganze<input id="whole" inputmode="numeric"></label><div class="fraction-input"><label>Zähler<input id="num" inputmode="numeric"></label><label>Nenner<input id="den" inputmode="numeric"></label></div></div><div class="math" id="live-preview"></div>`;
  if(task.answerType==='decimal')return `<label class="field">Dezimalzahl<input id="value" inputmode="decimal" placeholder="z. B. 0,75"></label>`;
  if(task.answerType==='number')return `<label class="field">Ergebnis<input id="value" inputmode="decimal"></label>`;
  if(task.answerType==='comparison')return `<div class="actions" role="group" aria-label="Vergleich auswählen"><button type="button" class="choice" data-value="<">&lt;</button><button type="button" class="choice" data-value="=">=</button><button type="button" class="choice" data-value=">">&gt;</button></div><input id="choice-value" type="hidden">`;
  if(task.answerType==='choice')return `<div class="actions">${task.options.map((o,i)=>`<button type="button" class="choice secondary" data-value="${String(o.value).replace(/"/g,'&quot;')}"><span data-tex="${o.tex||o.label}"></span></button>`).join('')}</div><input id="choice-value" type="hidden">`;
  return '';
}
export function wireInput(root,task){root.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{root.querySelectorAll('.choice').forEach(x=>x.classList.add('secondary'));b.classList.remove('secondary');root.querySelector('#choice-value').value=b.dataset.value}));const update=()=>{const p=root.querySelector('#live-preview');if(!p)return;const n=root.querySelector('#num')?.value,d=root.querySelector('#den')?.value,w=root.querySelector('#whole')?.value;if(n&&d&&d!=='0')p.dataset.tex=task.answerType==='mixed'&&w?`${w}\\,\\frac{${n}}{${d}}`:`\\frac{${n}}{${d}}`;else p.textContent='';renderAllMath(root)};root.querySelectorAll('input').forEach(i=>i.addEventListener('input',update));renderAllMath(root)}
export function collectAnswer(root,task){if(task.answerType==='fraction')return{numerator:root.querySelector('#num').value,denominator:root.querySelector('#den').value};if(task.answerType==='mixed')return{whole:root.querySelector('#whole').value,numerator:root.querySelector('#num').value,denominator:root.querySelector('#den').value};if(['decimal','number'].includes(task.answerType))return{value:root.querySelector('#value').value};if(['choice','comparison'].includes(task.answerType))return{value:root.querySelector('#choice-value').value};return{}}
