import {Fraction,fractionOfQuantity,wholeFromFractionPart} from '../core/fraction.js';
const pick=a=>a[Math.floor(Math.random()*a.length)];
const id=s=>`${s}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const F=(n,d)=>new Fraction(n,d);
export function generateBasic(skill,difficulty=1){
 const common={id:id(skill),skill,difficulty,hints:[],solutionSteps:[],requireReduced:false};
 if(skill==='fraction_meaning'){const f=pick([F(2,5),F(3,7),F(4,9)]);return{...common,type:'choice',answerType:'choice',promptTex:`\\frac{${f.numerator}}{${f.denominator}}`,promptText:'Welche Aussage beschreibt den Bruch richtig?',options:[{value:'a',label:`${f.numerator} von ${f.denominator} gleich großen Teilen`},{value:'b',label:`${f.denominator} von ${f.numerator} Teilen`},{value:'c',label:'Der Nenner sagt, wie viele Teile genommen werden.'}],correctAnswer:'a',hints:['Der Nenner beschreibt, in wie viele gleich große Teile das Ganze geteilt ist.']};}
 if(skill==='proper_improper'){const f=pick([F(7,4),F(3,8),F(9,9),F(11,6)]);const value=f.numerator<f.denominator?'echt':f.numerator===f.denominator?'schein':'unecht';return{...common,type:'choice',answerType:'choice',promptTex:`\\frac{${f.numerator}}{${f.denominator}}`,promptText:'Welche Art von Bruch ist das?',options:[{value:'echt',label:'echter Bruch'},{value:'unecht',label:'unechter Bruch'},{value:'schein',label:'Scheinbruch'}],correctAnswer:value,hints:['Vergleiche Zähler und Nenner.']};}
 if(skill==='mixed_numbers'){const whole=pick([1,2,3]),den=pick([4,5,6]),num=pick([1,2,3]);const correct=F(whole*den+num,den);return{...common,type:'fraction',answerType:'fraction',promptTex:`${whole}\\,\\frac{${num}}{${den}}`,promptText:'Wandle die gemischte Zahl in einen unechten Bruch um.',correctAnswer:correct,requireReduced:false,meta:{mode:'mixedToImproper',whole,denominator:den,numerator:num},hints:['Multipliziere die ganzen Teile mit dem Nenner.','Addiere danach den Zähler.'],solutionSteps:[`${whole}·${den}+${num}=${correct.numerator}`,`Nenner bleibt ${den}`]};}
 if(skill==='simplify'){const base=pick([F(2,3),F(3,4),F(4,5),F(5,7)]),k=pick([2,3,4]);const shown=base.expand(k);return{...common,type:'fraction',answerType:'fraction',promptTex:`\\frac{${shown.numerator}}{${shown.denominator}}`,promptText:'Kürze vollständig.',correctAnswer:base,requireReduced:true,hints:['Suche einen gemeinsamen Teiler von Zähler und Nenner.',`Der ggT ist ${k}.`],solutionSteps:[`${shown.numerator}:${k}=${base.numerator}`,`${shown.denominator}:${k}=${base.denominator}`]};}
 if(skill==='expand'||skill==='equivalence'){const base=pick([F(2,3),F(3,5),F(4,7)]),k=pick([2,3,4]);return{...common,type:'fraction',answerType:'fraction',promptTex:`\\frac{${base.numerator}}{${base.denominator}}`,promptText:`Erweitere mit ${k}.`,correctAnswer:base.expand(k),hints:['Multipliziere Zähler und Nenner mit derselben Zahl.']};}
 if(skill==='compare'){const a=pick([F(1,2),F(2,3),F(3,4),F(5,6)]),b=pick([F(2,5),F(3,5),F(4,5),F(7,8)]);return{...common,type:'comparison',answerType:'comparison',promptTex:`\\frac{${a.numerator}}{${a.denominator}}\;?\;\\frac{${b.numerator}}{${b.denominator}}`,promptText:'Setze <, > oder = ein.',correctAnswer:a.compare(b)<0?'<':a.compare(b)>0?'>':'=',hints:['Bringe die Brüche auf einen gemeinsamen Nenner oder vergleiche ihre Größe mit 1/2 und 1.']};}
 if(skill==='fraction_to_decimal'){const f=pick([F(1,2),F(1,4),F(3,4),F(1,5),F(3,5)]);return{...common,type:'decimal',answerType:'decimal',promptTex:`\\frac{${f.numerator}}{${f.denominator}}`,promptText:'Schreibe als Dezimalzahl.',correctAnswer:f,hints:['Teile Zähler durch Nenner.']};}
 if(skill==='decimal_to_fraction'){const f=pick([F(1,2),F(1,4),F(3,4),F(2,5),F(3,5)]);return{...common,type:'fraction',answerType:'fraction',promptText:`Schreibe ${String(f.toDecimal()).replace('.',',')} als vollständig gekürzten Bruch.`,correctAnswer:f,requireReduced:true,hints:['Denke an Zehntel oder Hundertstel und kürze anschließend.']};}
 if(skill==='fraction_of_quantity'){const f=pick([F(1,3),F(2,5),F(3,4)]),unit=pick([4,5,6]),quantity=f.denominator*unit;return{...common,type:'number',answerType:'number',promptTex:`\\frac{${f.numerator}}{${f.denominator}}\\text{ von }${quantity}`,promptText:'Berechne den Bruchteil.',correctAnswer:fractionOfQuantity(f,quantity),hints:[`Teile zuerst ${quantity} durch ${f.denominator}.`,`Multipliziere das Ergebnis mit ${f.numerator}.`],solutionSteps:[`${quantity}:${f.denominator}=${unit}`,`${unit}·${f.numerator}=${unit*f.numerator}`]};}
 if(skill==='whole_from_part'){const f=pick([F(1,3),F(2,5),F(3,4)]),unit=pick([4,6,8]),part=unit*f.numerator;return{...common,type:'number',answerType:'number',promptTex:`\\frac{${f.numerator}}{${f.denominator}}\\text{ sind }${part}`,promptText:'Wie groß ist das Ganze?',correctAnswer:wholeFromFractionPart(f,part),hints:[`${f.numerator} Teile sind ${part}. Bestimme zuerst 1 Teil.`,`Danach brauchst du ${f.denominator} Teile.`],solutionSteps:[`${part}:${f.numerator}=${unit}`,`${unit}·${f.denominator}=${unit*f.denominator}`]};}
 if(skill==='number_line'){const targets=pick([[0,1,4,F(3,4)],[0,2,8,F(5,4)],[0,2,6,F(4,3)]]);return{...common,type:'numberLine',answerType:'numberLine',promptText:'Setze den Bruch an die richtige Stelle auf dem Zahlenstrahl.',promptTex:`\\frac{${targets[3].numerator}}{${targets[3].denominator}}`,correctAnswer:targets[3],numberLine:{min:targets[0],max:targets[1],subdivisions:targets[2],target:targets[3].toDecimal(),mode:'place',tolerance:.07},hints:['Überlege zuerst, zwischen welchen ganzen Zahlen der Bruch liegt.']};}
 return null;
}
