import {Fraction} from '../core/fraction.js';
const pick=a=>a[Math.floor(Math.random()*a.length)];
const id=s=>`${s}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export function generateMixedNumbers(difficulty=1){
  const den=pick([4,5,6,8]),whole=pick([1,2,3]),num=pick(Array.from({length:Math.min(den-1,4)},(_,i)=>i+1));
  if(Math.random()<.5){const improper=new Fraction(whole*den+num,den);return{id:id('mixed_numbers'),skill:'mixed_numbers',difficulty,type:'fraction',answerType:'fraction',promptText:'Wandle die gemischte Zahl in einen unechten Bruch um.',promptTex:`${whole}\\,\\frac{${num}}{${den}}`,correctAnswer:improper,requireReduced:false,meta:{mode:'mixedToImproper',whole,numerator:num,denominator:den},hints:['Multipliziere die ganzen Teile mit dem Nenner.','Addiere danach den Zähler. Der Nenner bleibt gleich.'],solutionSteps:[`${whole}·${den}+${num}=${whole*den+num}`,`\\frac{${whole*den+num}}{${den}}`]};}
  const improper=new Fraction(whole*den+num,den);return{id:id('mixed_numbers'),skill:'mixed_numbers',difficulty,type:'mixed',answerType:'mixed',promptText:'Wandle den unechten Bruch in eine gemischte Zahl um.',promptTex:`\\frac{${improper.numerator}}{${improper.denominator}}`,correctAnswer:improper,requireReduced:true,hints:['Wie oft passt der Nenner vollständig in den Zähler?','Der Rest wird zum neuen Zähler.'],solutionSteps:[`${improper.numerator}:${den}=${whole} Rest ${num}`,`${whole}\\,\\frac{${num}}{${den}}`]};
}
export function generateEquivalence(difficulty=1){const base=pick([new Fraction(1,2),new Fraction(2,3),new Fraction(3,4),new Fraction(3,5)]),k=pick([2,3,4]);const eq=base.expand(k);const wrong=new Fraction(eq.numerator+1,eq.denominator);return{id:id('equivalence'),skill:'equivalence',difficulty,type:'choice',answerType:'choice',promptText:'Welcher Bruch ist gleichwertig?',promptTex:`\\frac{${base.numerator}}{${base.denominator}}`,options:[{value:'eq',tex:`\\frac{${eq.numerator}}{${eq.denominator}}`},{value:'wrong',tex:`\\frac{${wrong.numerator}}{${wrong.denominator}}`},{value:'swap',tex:`\\frac{${base.denominator}}{${base.numerator}}`}],correctAnswer:'eq',hints:['Gleichwertige Brüche entstehen, wenn Zähler und Nenner mit derselben Zahl multipliziert oder dividiert werden.'],solutionSteps:[`\\frac{${base.numerator}}{${base.denominator}}=\\frac{${eq.numerator}}{${eq.denominator}}`]};}
